In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_csv(
    r"D:\Election Data Project\data\raw\Elections.csv",
    encoding="cp1252"
)

df.head()

,Country,country_type,election_year,election_date,largest_electorate,largest_winner,second_electorate,second_winner,third_electorate,third_winner,national_winner
0,United States,Developed,1964,11/3/1964,California,Lyndon B. Johnson,Texas,Lyndon B. Johnson,Florida,Lyndon B. Johnson,Lyndon B. Johnson
1,United States,Developed,1968,11/5/1968,California,Richard Nixon,Texas,Richard Nixon,Florida,Lyndon B. Johnson,Richard Nixon
2,United States,Developed,1972,11/7/1972,California,Richard Nixon,Texas,Richard Nixon,Florida,Richard Nixon,Richard Nixon
3,United States,Developed,1976,11/2/1976,California,Jimmy Carter,Texas,Jimmy Carter,Florida,Jimmy Carter,Jimmy Carter
4,United States,Developed,1980,11/4/1980,California,Ronald Reagan,Texas,Ronald Reagan,Florida,Ronald Reagan,Ronald Reagan

In [59]:
df.head()

,Country,country_type,election_year,election_date,largest_electorate,largest_winner,second_electorate,second_winner,third_electorate,third_winner,national_winner
0,United States,Developed,1964,11/3/1964,California,Lyndon B. Johnson,Texas,Lyndon B. Johnson,Florida,Lyndon B. Johnson,Lyndon B. Johnson
1,United States,Developed,1968,11/5/1968,California,Richard Nixon,Texas,Richard Nixon,Florida,Lyndon B. Johnson,Richard Nixon
2,United States,Developed,1972,11/7/1972,California,Richard Nixon,Texas,Richard Nixon,Florida,Richard Nixon,Richard Nixon
3,United States,Developed,1976,11/2/1976,California,Jimmy Carter,Texas,Jimmy Carter,Florida,Jimmy Carter,Jimmy Carter
4,United States,Developed,1980,11/4/1980,California,Ronald Reagan,Texas,Ronald Reagan,Florida,Ronald Reagan,Ronald Reagan

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             57 non-null     object
 1   country_type        57 non-null     object
 2   election_year       57 non-null     int64
 3   election_date       57 non-null     object
 4   largest_electorate  57 non-null     object
 5   largest_winner      57 non-null     object
 6   second_electorate   57 non-null     object
 7   second_winner       57 non-null     object
 8   third_electorate    57 non-null     object
 9   third_winner        57 non-null     object
 10  national_winner     57 non-null     object
dtypes: int64(1), object(10)
memory usage: 5.0+ KB

### Data Type Conversion

In [61]:
df["election_date"] = pd.to_datetime(
    df["election_date"]
)

In [62]:
df.dtypes

Country                       object
country_type                  object
election_year                  int64
election_date         datetime64[ns]
largest_electorate            object
largest_winner                object
second_electorate             object
second_winner                 object
third_electorate              object
third_winner                  object
national_winner               object
dtype: object

In [63]:
df.isnull().sum()

Country               0
country_type          0
election_year         0
election_date         0
largest_electorate    0
largest_winner        0
second_electorate     0
second_winner         0
third_electorate      0
third_winner          0
national_winner       0
dtype: int64

In [64]:
df["country_type"].value_counts()

country_type
Developed     34
Developing    23
Name: count, dtype: int64

In [65]:
print("Minimum Year:", df["election_year"].min())
print("Maximum Year:", df["election_year"].max())

Minimum Year: 1964
Maximum Year: 2024

In [66]:
df[df.duplicated(subset=["Country", "election_year"])]

Empty DataFrame
Columns: [Country, country_type, election_year, election_date, largest_electorate, largest_winner, second_electorate, second_winner, third_electorate, third_winner, national_winner]
Index: []

In [67]:
df["election_date"].describe()

count                               57
mean     2002-02-10 02:56:50.526315776
min                1964-11-03 00:00:00
25%                1991-01-13 00:00:00
50%                2004-09-20 00:00:00
75%                2014-10-26 00:00:00
max                2024-11-05 00:00:00
Name: election_date, dtype: object

In [68]:
df["election_year"].dtype

dtype('int64')

In [69]:
df.describe(include="all")

,Country,country_type,election_year,election_date,largest_electorate,largest_winner,second_electorate,second_winner,third_electorate,third_winner,national_winner
count,57,57,57.000000,57,57,57,57,57,57,57,57
unique,6,2,NaN,NaN,7,39,6,35,6,38,38
top,United States,Developed,NaN,NaN,California,Prabowo Subianto,Texas,Mahinda Rajapaksa,Florida,Mahinda Rajapaksa,Lula
freq,16,34,NaN,NaN,16,3,16,3,16,3,3
mean,NaN,NaN,2001.456140,2002-02-10 02:56:50.526315776,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1964.000000,1964-11-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,1991.000000,1991-01-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2004.000000,2004-09-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2014.000000,2014-10-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2024.000000,2024-11-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,15.559873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df.to_csv(
    r"D:\Election Data Project\data\processed\Elections_Clean.csv",
    index=False,
    encoding="utf-8"
)